# Generated by Django 5.1.3 on 2024-11-30 08:39

import django.db.models.deletion
import users.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_sized_photo', models.ImageField(blank=True, null=True, upload_to=users.validators.get_unique_filename, validators=[users.validators.validate_image_file_extension])),
                ('signature', models.ImageField(blank=True, null=True, upload_to=users.validators.get_unique_filename, validators=[users.validators.validate_image_file_extension])),
                ('citizenship_front', models.ImageField(blank=True, null=True, upload_to=users.validators.get_unique_filename, validators=[users.validators.validate_image_file_extension])),
                ('citizenship_back', models.ImageField(blank=True, null=True, upload_to=users.validators.get_unique_filename, validators=[users.validators.validate_image_file_extension])),
                ('location_map', models.ImageField(blank=True, null=True, upload_to=users.validators.get_unique_filename, validators=[users.validators.validate_image_file_extension])),
                ('selfie_with_citizenship', models.ImageField(blank=True, null=True, upload_to=users.validators.get_unique_filename, validators=[users.validators.validate_image_file_extension])),
                ('is_draft_docs', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
